#! /src/bin/python
from dirwatch import Dirwatch
import sys, subprocess, dirwatch



if __name__ == '__main__':
    def f (changed_files, removed_files):
        print len(changed_files)
        print 'Removed', len(removed_files)

    dirs = sys.argv[1:]
    if not dirs:
        dirs = ["."]

    
    Dirwatch(dirs, f, 1).watch()